name: todo_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  path_provider: ^2.1.1
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  drag_and_drop_lists: ^0.3.3
  intl: ^0.18.1
  flutter_local_notifications: ^16.2.0
  json_annotation: ^4.8.1
  get: ^4.6.6
  flutter_screenutil:
#  flutter_native_splash:

dev_dependencies:
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


#flutter_native_splash:
#  color: "#42a5f5"
#  image: assets/image/logo.jpg
#  android_12:
#    image: assets/image/logo.jpg
#  android: true
#  ios: true
#  web: false

flutter:
  assets:
    - assets/image/


  uses-material-design: true

